baseURL: "https://aimeegee.github.io/aimeesnotes"
languageCode: "en-us"
title: "Aimee's Note"
theme: "blank"

# menu of home, posts, categories, tag
menu:
  main:
    - name: "Home"
      weight: 1
      url: "/"
    - name: "Categories"
      weight: 2
      url: "/categories/"
    - name: "Tags"
      weight: 3
      url: "/tags/"
    - name: "Posts"
      weight: 4
      url: "/posts/"
    - name: "Dev"
      weight: 5
      url: "/dev/"
    - name: "Study"
      weight: 6
      url: "/study/"
